name: Publish (Development)

on:
  push:
    branches:
    - live

jobs:
  publish_to_backend:
    name: "Publish to Backend"

    runs-on: [self-hosted, Linux]

    steps:
    - name: checkout engine without LFS
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull ProjectSystem docker image
      run: docker pull ghcr.io/nginetechnologies/projectsystem:latest
    - name: Publish to backend
      run: |
        docker run -v ${{ github.workspace }}:/repo ghcr.io/nginetechnologies/projectsystem:latest +register_backend_assets /repo/Components/PhysicsBody.nproject/Assets.nassetdb
        docker run -v ${{ github.workspace }}:/repo ghcr.io/nginetechnologies/projectsystem-dev:latest +register_backend_assets /repo/Components/DirectionalLight.nproject/Assets.nassetdb
        docker run -v ${{ github.workspace }}:/repo ghcr.io/nginetechnologies/projectsystem-dev:latest +register_backend_assets /repo/Components/PointLight.nproject/Assets.nassetdb
        docker run -v ${{ github.workspace }}:/repo ghcr.io/nginetechnologies/projectsystem-dev:latest +register_backend_assets /repo/Components/SpotLight.nproject/Assets.nassetdb